"""Security package initialization."""
from app.core.security.sanitizers import (
    FilenameSanitizer,
    DocumentSanitizer,
    PromptSanitizer,
    ToolValidator,
)
from app.core.security.security_models import (
    RoleName,
    ActionType,
    Permission,
    Role,
    PolicyRule,
    APIKey,
    SecretRecord,
    AuditRecord,
    SecurityEvent,
    ComplianceReport,
    TenantContext,
)
from app.core.security.security_metrics import security_metrics_tracker, SecurityMetricsTracker
from app.core.security.rbac import rbac_engine, RBACEngine
from app.core.security.policy_engine import policy_engine, PolicyEngine
from app.core.security.tenant_security import tenant_security, TenantSecurity
from app.core.security.secret_manager import secret_manager, SecretManager
from app.core.security.api_keys import api_key_manager, APIKeyManager
from app.core.security.rate_policy import rate_policy_engine, RatePolicyEngine
from app.core.security.audit_logger import audit_logger, AuditLogger
from app.core.security.security_events import security_event_bus, SecurityEventBus
from app.core.security.compliance import compliance_engine, ComplianceEngine
from app.core.security.middleware import SecurityContextMiddleware

from app.core.security.security_types import (
    Architecture,
    FileFormat,
    ThreatSeverity,
    AnalysisStatus,
    BinarySection,
    BinaryImport,
    BinaryExport,
    BinarySymbol,
    BinaryInstruction,
    BinaryFunction,
    BinaryString,
    FileFingerprint,
    BinaryMetadata,
    MalwareSample,
    IOC,
    ThreatIndicator,
    ThreatActorProfile,
    SecurityFinding,
    VulnerabilityFinding,
    StaticAnalysisResult,
    SandboxResult,
    DynamicAnalysisResult,
    RiskAssessment as SecurityResearchRiskAssessment,
    ForensicArtifact,
    AttackSimulation,
    DetectionRule,
    ThreatReport,
    ReverseEngineeringSession,
    SecurityMetrics,
    SecurityDashboardState,
)
from app.core.security.security_config import security_config, SecurityResearchConfig
from app.core.security.security_registry import security_registry, SecurityRegistry
from app.core.security.security_context import unified_security_context, UnifiedSecurityContext
from app.core.security.security_pipeline import security_pipeline, SecurityPipeline
from app.core.security.security_events import SecurityResearchEventType, publish_security_event
from app.core.security.security_manager import enterprise_security_manager, EnterpriseSecurityManager
from app.core.security.operations import security_operations_manager, SecurityOperationsManager, playbook_engine, PlaybookEngine
from app.core.security.platform import enterprise_security_platform, EnterpriseSecurityPlatform

__all__ = [
    "FilenameSanitizer",
    "DocumentSanitizer",
    "PromptSanitizer",
    "ToolValidator",
    "RoleName",
    "ActionType",
    "Permission",
    "Role",
    "PolicyRule",
    "APIKey",
    "SecretRecord",
    "AuditRecord",
    "SecurityEvent",
    "ComplianceReport",
    "TenantContext",
    "security_metrics_tracker",
    "SecurityMetricsTracker",
    "rbac_engine",
    "RBACEngine",
    "policy_engine",
    "PolicyEngine",
    "tenant_security",
    "TenantSecurity",
    "secret_manager",
    "SecretManager",
    "api_key_manager",
    "APIKeyManager",
    "rate_policy_engine",
    "RatePolicyEngine",
    "audit_logger",
    "AuditLogger",
    "security_event_bus",
    "SecurityEventBus",
    "compliance_engine",
    "ComplianceEngine",
    "SecurityContextMiddleware",
    # Security Research Extensions
    "Architecture",
    "FileFormat",
    "ThreatSeverity",
    "AnalysisStatus",
    "BinarySection",
    "BinaryImport",
    "BinaryExport",
    "BinarySymbol",
    "BinaryInstruction",
    "BinaryFunction",
    "BinaryString",
    "FileFingerprint",
    "BinaryMetadata",
    "MalwareSample",
    "IOC",
    "ThreatIndicator",
    "ThreatActorProfile",
    "SecurityFinding",
    "VulnerabilityFinding",
    "StaticAnalysisResult",
    "SandboxResult",
    "DynamicAnalysisResult",
    "SecurityResearchRiskAssessment",
    "ForensicArtifact",
    "AttackSimulation",
    "DetectionRule",
    "ThreatReport",
    "ReverseEngineeringSession",
    "SecurityMetrics",
    "SecurityDashboardState",
    "security_config",
    "SecurityResearchConfig",
    "security_registry",
    "SecurityRegistry",
    "unified_security_context",
    "UnifiedSecurityContext",
    "security_pipeline",
    "SecurityPipeline",
    "SecurityResearchEventType",
    "publish_security_event",
    "enterprise_security_manager",
    "EnterpriseSecurityManager",
    "security_operations_manager",
    "SecurityOperationsManager",
    "playbook_engine",
    "PlaybookEngine",
    "enterprise_security_platform",
    "EnterpriseSecurityPlatform",
]
