"""
Intelligence Types and Models for Doxa AI Operating System.

Defines Pydantic data models for ExecutionStrategy, AdaptiveExecutionGraph,
GlobalContextBlock, ScheduledTask, OptimizationCacheEntry, PipelineTrace,
AutonomousPolicy, KnowledgeFlowRecord, KernelExecutionState, and SystemDashboardMetrics.
"""

import time
import uuid
from enum import Enum
from typing import Dict, Any, List, Optional, Set
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ExecutionMode(str, Enum):
    """Execution mode determined by the decision engine."""
    DIRECT = "direct"
    FAST = "fast"
    BALANCED = "balanced"
    DEEP_REASONING = "deep_reasoning"
    AUTONOMOUS_AGENT = "autonomous_agent"
    HYBRID_WORKFLOW = "hybrid_workflow"


class TaskPriority(str, Enum):
    """Priority levels for background scheduled intelligence tasks."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TaskType(str, Enum):
    """Types of asynchronous intelligence tasks."""
    EMBEDDING_GENERATION = "embedding_generation"
    RETRIEVAL_HYBRID = "retrieval_hybrid"
    CROSS_ENCODER_RERANK = "cross_encoder_rerank"
    MEMORY_CONSOLIDATION = "memory_consolidation"
    WORKFLOW_EXECUTION = "workflow_execution"
    EVALUATION = "evaluation"
    LEARNING_JOB = "learning_job"
    KNOWLEDGE_GRAPH_UPDATE = "knowledge_graph_update"
    BACKGROUND_INDEXING = "background_indexing"


class ExecutionStatus(str, Enum):
    """Lifecycle status of a kernel execution."""
    PENDING = "pending"
    INITIALIZING = "initializing"
    ROUTING = "routing"
    EXECUTING = "executing"
    OPTIMIZING = "optimizing"
    FINALIZING = "finalizing"
    COMPLETED = "completed"
    FAILED = "failed"
    RECOVERED = "recovered"


# ---------------------------------------------------------------------------
# Adaptive Decision Models
# ---------------------------------------------------------------------------

class DecisionGraphNode(BaseModel):
    """A single subsystem execution node in the adaptive decision graph."""
    node_id: str
    subsystem: str  # rag, memory, planner, reasoning, multi_agent, python_sandbox, web_search, workflow, eval, long_term_memory
    enabled: bool = True
    confidence: float = 0.9
    estimated_latency_ms: float = 50.0
    prerequisites: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AdaptiveExecutionGraph(BaseModel):
    """Adaptive execution graph generated by the Decision Engine."""
    graph_id: str = Field(default_factory=lambda: f"graph_{uuid.uuid4().hex[:8]}")
    execution_mode: ExecutionMode = ExecutionMode.BALANCED
    nodes: List[DecisionGraphNode] = Field(default_factory=list)
    should_run_rag: bool = True
    should_run_memory: bool = True
    should_run_planner: bool = False
    should_run_multi_agent: bool = False
    should_execute_python: bool = False
    should_execute_web_search: bool = False
    should_execute_workflow: bool = False
    should_run_evaluation: bool = True
    should_update_long_term_memory: bool = True
    estimated_total_latency_ms: float = 200.0
    latency_budget_ms: float = 5000.0
    complexity_score: float = 0.5
    created_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Global Context Models
# ---------------------------------------------------------------------------

class ContextItem(BaseModel):
    """Individual context element with metadata for ranking and filtering."""
    item_id: str = Field(default_factory=lambda: f"ctx_{uuid.uuid4().hex[:8]}")
    source_type: str  # history, rag, semantic_memory, long_term_memory, episodic_memory, preference, knowledge_graph, workflow, planner, reasoning, eval, tool
    content: str
    tokens_count: int = 0
    relevance_score: float = 1.0
    recency_timestamp: float = Field(default_factory=time.time)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class UnifiedGlobalContext(BaseModel):
    """Merged, deduplicated, ranked, compressed, and token-budgeted global context."""
    context_id: str = Field(default_factory=lambda: f"ugc_{uuid.uuid4().hex[:8]}")
    items: List[ContextItem] = Field(default_factory=list)
    total_tokens: int = 0
    max_token_budget: int = 4096
    deduplicated_count: int = 0
    clustered_group_count: int = 0
    compressed: bool = False
    compression_ratio: float = 1.0
    merged_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Scheduler Models
# ---------------------------------------------------------------------------

class IntelligenceTask(BaseModel):
    """An asynchronous intelligence background task."""
    task_id: str = Field(default_factory=lambda: f"task_{uuid.uuid4().hex[:8]}")
    task_type: TaskType
    priority: TaskPriority = TaskPriority.MEDIUM
    payload: Dict[str, Any] = Field(default_factory=dict)
    scheduled_at: float = Field(default_factory=time.time)
    started_at: Optional[float] = None
    completed_at: Optional[float] = None
    status: str = "PENDING"
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# Execution Optimizer Models
# ---------------------------------------------------------------------------

class OptimizationCacheEntry(BaseModel):
    """Cached result of repeated expensive computations."""
    cache_key: str
    computation_type: str  # retrieval, embedding, planning, reasoning, tool, workflow, memory_write
    result: Any
    hit_count: int = 1
    cached_at: float = Field(default_factory=time.time)
    ttl_seconds: float = 300.0


# ---------------------------------------------------------------------------
# Pipeline Profiler Models
# ---------------------------------------------------------------------------

class ComponentLatencyTrace(BaseModel):
    """Latency and resource measurement for a single subsystem."""
    component_name: str
    duration_ms: float = 0.0
    start_time: float = Field(default_factory=time.time)
    end_time: float = 0.0
    tokens_consumed: int = 0
    memory_used_mb: float = 0.0
    estimated_cost_usd: float = 0.0
    success: bool = True
    metadata: Dict[str, Any] = Field(default_factory=dict)


class PipelineTrace(BaseModel):
    """Complete end-to-end execution trace for a request."""
    trace_id: str = Field(default_factory=lambda: f"trace_{uuid.uuid4().hex[:10]}")
    request_id: str = "req_unknown"
    total_duration_ms: float = 0.0
    component_traces: List[ComponentLatencyTrace] = Field(default_factory=list)
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    cache_hits: int = 0
    cache_misses: int = 0
    started_at: float = Field(default_factory=time.time)
    completed_at: float = 0.0


# ---------------------------------------------------------------------------
# Autonomous Optimization Models
# ---------------------------------------------------------------------------

class PolicyRecommendation(BaseModel):
    """Learned optimal policy for a subsystem."""
    subsystem: str
    best_strategy: str
    confidence: float = 0.95
    evidence_count: int = 1
    improvement_pct: float = 12.0
    updated_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Knowledge Flow Models
# ---------------------------------------------------------------------------

class KnowledgeFlowStep(BaseModel):
    """Record of knowledge propagation across subsystems."""
    step_id: str = Field(default_factory=lambda: f"kf_{uuid.uuid4().hex[:8]}")
    from_subsystem: str
    to_subsystem: str
    payload_summary: str
    data_hash: str
    timestamp: float = Field(default_factory=time.time)


class KnowledgeFlowRecord(BaseModel):
    """Trace of a complete knowledge flow lifecycle."""
    flow_id: str = Field(default_factory=lambda: f"kflow_{uuid.uuid4().hex[:8]}")
    request_id: str
    steps: List[KnowledgeFlowStep] = Field(default_factory=list)
    deduplicated_transfers: int = 0
    created_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# AI OS Kernel State
# ---------------------------------------------------------------------------

class KernelExecutionState(BaseModel):
    """Maintained state of a request passing through the AI OS Kernel."""
    execution_id: str = Field(default_factory=lambda: f"exec_{uuid.uuid4().hex[:10]}")
    request_id: str = "req_default"
    user_id: str = "anonymous"
    tenant_id: str = "default"
    prompt: str = ""
    status: ExecutionStatus = ExecutionStatus.PENDING
    graph: Optional[AdaptiveExecutionGraph] = None
    context: Optional[UnifiedGlobalContext] = None
    trace: Optional[PipelineTrace] = None
    flow: Optional[KnowledgeFlowRecord] = None
    output_text: str = ""
    error_message: Optional[str] = None
    started_at: float = Field(default_factory=time.time)
    finalized_at: Optional[float] = None


# ---------------------------------------------------------------------------
# Dashboard Operational Metrics
# ---------------------------------------------------------------------------

class SystemDashboardMetrics(BaseModel):
    """Live operational intelligence metrics for the AI Operating System."""
    active_agents: int = 0
    running_workflows: int = 0
    memory_usage_mb: float = 0.0
    retrieval_hit_rate: float = 0.0
    cache_hit_rate: float = 0.0
    reasoning_quality_score: float = 0.0
    planner_success_rate: float = 0.0
    evaluation_score: float = 0.0
    worker_utilization_pct: float = 0.0
    queue_lengths: Dict[str, int] = Field(default_factory=dict)
    token_consumption_rate_tps: float = 0.0
    average_latency_ms: float = 0.0
    system_confidence_score: float = 0.95
    total_requests_processed: int = 0
    updated_at: float = Field(default_factory=time.time)
